on:
    push:
        branches:
            -   docker

jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: jim137
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                file: ./Docker/Dockerfile
                push: true
                tags: jim137/twasap:latest
