on:
    push:
        branches:
            -   main
    schedule:
      - cron:   "*/30 * * * *" # default run every 30 minutes
    workflow_dispatch:

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
            TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        steps:
            -   uses: actions/checkout@v4
            -   name: Checkout output branch
                run: |
                    if (git ls-remote --exit-code --heads origin output); then git fetch origin output:output; else git checkout -b output; fi
                    git checkout output
            -   name: Set up Python 3.11
                uses: actions/setup-python@v4
                with:
                    python-version: 3.11
            -   name: Install dependencies and create twarc config
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    printf "[default]\nconsumer_key = ${{ secrets.TWITTER_CONSUMER_KEY }}\nconsumer_secret = ${{ secrets.TWITTER_CONSUMER_SECRET }}\naccess_token = ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}\naccess_token_secret = ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" > ~/.twarc
            -   name: Run
                run: | 
                    python -m TwASAP
            -   name: Commit and push to output branch
                run: |
                    git config --global user.name "GitHub Actions"
                    git config --global user.email "Action@Github.com"
                    timestamp=$(date -u)
                    git add . || true
                    git commit -m "Latest data: ${timestamp}" || true
                    git push -u origin output || true
